version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: easypay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easypay
      MYSQL_USER: easypay_user
      MYSQL_PASSWORD: easypay_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: